import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "../component/Footer/index";
import Navbar from "../component/Navbar/index";

const inter = Lato({ weight: ["400", "700", "900"], subsets: ["latin"] });

export const metadata = {
    title: "Othr",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
